#!/usr/bin/env python3
#
# Copyright (C) 2026  Vates SAS
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import configparser

from xcp_storage.rpc.server import RpcApiServer

# ==============================================================================

DEFAULT_ADDRESS = "0.0.0.0"
DEFAULT_PORT = 3630

# ------------------------------------------------------------------------------

if __name__ == "__main__":
    config = configparser.ConfigParser()
    config.read("/etc/xcp-storage/rpc.conf")

    address = config.get("network", "address", fallback=DEFAULT_ADDRESS)
    port = config.getint("network", "port", fallback=DEFAULT_PORT)

    # TODO: Use SSL context.
    api_server = RpcApiServer(address, port, ssl_context=None)
    api_server.run()
